version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      api-prod:
        ipv4_address: 172.19.0.5
    ports:
      - "27017:27017"
    volumes:
      - "C:\\Program Files\\MongoDB\\Server\\6.0\\data:/data/db"
    restart: always

  fastapi-app:
    container_name: fastapi-app
    image: emagmir/fast-api-cicd
    networks:
      api-prod:
    ports:
      - "8000:8000"
    restart: always

networks:
  api-prod:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1