Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "my-jenkins"
    config.vm.network "private_network", ip: "192.168.56.2"
    config.vm.boot_timeout = 6000

    config.vm.network "forwarded_port", guest: 8080, host: 9000
    
    config.vm.provider "virtualbox" do |v|
        v.name = "my-jenkins"
        v.memory = 1024
        v.cpus = 2
      end
      
    config.vm.provision "shell", path: "prov-jenkins.sh"
    end