Vagrant.configure("2") do |config|
    config.vm.define "eks" do |eks|
      eks.vm.box = "ubuntu/bionic64"
      eks.vm.network "private_network", ip: "192.168.56.15"
      eks.vm.boot_timeout = 600
  
      eks.vm.provider "virtualbox" do |v|
        v.name = "eks"
        v.memory = 1024
        v.cpus = 2
      end
      eks.vm.hostname = "eks"
      eks.vm.provision "shell", path: "eks_prov.sh"
    end
end