name: TF_ECS_App_deploy
on:
  push:
    branches:
      - "tf-ecs-git-actions"
    paths:
      - fast-app/**
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECS_SERVICE: my-ecs-service
  ECS_CLUSTER: fast-api-ecs-cluster
  CONTAINER_NAME: fast-api-cont-2

jobs:
  BUILD_AND_DEPLOY:
    runs-on: ubuntu-latest
    defaults:
      run:
          shell: bash
          working-directory: ./fast-app

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          ref: 'tf-ecs-git-actions'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:fast-app"
          push: True
          tags: emagmir/fast-api-cicd:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition my-ecs-task --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: fast-app/task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: emagmir/fast-api-cicd:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true