name: Fast-api CICD
on:
  push:
    paths:
      - ".github/workflows/main.yml"
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        run: echo "workflow works"