name: TF EKS CI/CD
on: [push, workflow_dispatch]
env:
  AWS_REGION: us-east-1

jobs:
  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          ref: 'kube-git-actions'

      - name: Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.AWS_REGISTRY }}
          repo: fast-api-ecr
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          daemon_off: false
          dockerfile: ./dockerfile
          context: ./